# -*- mode: python ; coding: utf-8 -*-

import os
import sys
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

# 收集所有需要的数据文件
datas = collect_data_files('DrissionPage')
datas += collect_data_files('feapder')
datas += collect_data_files('DrissionPage.easy_set')
datas += collect_data_files('DrissionPage.settings')
datas += collect_data_files('DrissionPage.common')
datas += collect_data_files('DrissionPage.errors')
datas += collect_data_files('DrissionPage._elements')
datas += collect_data_files('DrissionPage._pages')
datas += collect_data_files('DrissionPage.DrissionPage')

# 收集所有子模块
hiddenimports = []
hiddenimports.extend(collect_submodules('feapder'))
hiddenimports.extend(collect_submodules('DrissionPage'))
hiddenimports.extend(collect_submodules('DrissionPage.common'))
hiddenimports.extend(collect_submodules('DrissionPage.errors'))
hiddenimports.extend(collect_submodules('DrissionPage._elements'))
hiddenimports.extend(collect_submodules('DrissionPage._pages'))
hiddenimports.extend(collect_submodules('DrissionPage.DrissionPage'))
hiddenimports.extend(collect_submodules('DrissionPage.easy_set'))
hiddenimports.extend(collect_submodules('DrissionPage.settings'))

# 添加其他必要的隐藏导入
hiddenimports.extend([
    'concurrent.futures',
    'tkinter',
    'tkinter.ttk',
    'tkinter.messagebox',
    'tkinter.filedialog',
    'hashlib',
    'json',
    'base64',
    're',
    'argparse',
    'threading',
    'logging',
    'time',
    'ssl',
    'urllib',
    'urllib.parse',
    'urllib.request',
    'urllib.error',
    'urllib.robotparser',
    'http',
    'http.client',
    'email',
    'email.mime',
    'email.mime.text',
    'email.mime.multipart',
    'socket',
    'selectors',
    'collections',
    'collections.abc',
    'copy',
    'datetime',
    'heapq',
    'itertools',
    'keyword',
    'operator',
    'reprlib',
    'tempfile',
    'weakref',
    'zipfile',
    'pprint',
    'types',
    'functools',
    'contextlib',
    'warnings',
    'abc',
    'locale',
    'textwrap',
    'traceback',
    'inspect',
    'ast',
    'symtable',
    'tokenize',
    'token',
    'linecache',
    'os.path',
    'ntpath',  # Windows路径处理
    'genericpath',
    'posix',
    'stat',
    'warnings',
    'errno',
    'fnmatch',
    'random',
    'sre_compile',
    'sre_constants',
    'sre_parse',
    '_sre',
    '_locale',
    'copyreg',
    'stringprep',
    'urllib.parse',
    'urllib.error',
    'urllib.request',
    'urllib.response',
    'urllib.robotparser',
    'http',
    'http.client',
    'http.cookiejar',
    'http.cookies',
    'encodings',
    'encodings.idna',
    'encodings.utf_8',
    'encodings.latin_1',
    'codecs',
    'string',
    'struct',
    'calendar',
    'ftplib',
    'netrc',
    'mimetypes',
    'cgi',
    'uuid',
    'platform',
    'subprocess',
    'signal',
    'resource',
    'pwd',
    'grp',
    'termios',
    'tty',
    'pty',
    'fcntl',
    'select',
    'pstats',
    'profile',
    'pickle',
    'shelve',
    'shutil',
    'glob',
    'fnmatch',
    'getopt',
    'getpass',
    'setsignal',
    'ossaudiodev',
    'audioop',
    'aifc',
    'sunau',
    'wave',
    'chunk',
    'colorsys',
    'webbrowser',
    'cgi',
    'cgitb',
    'wsgiref',
    'urllib3',
    'requests',
    'lxml',
    'lxml.etree',
    'lxml.html',
    'cssselect',
    'selenium',
    'selenium.webdriver',
    'selenium.webdriver.common',
    'selenium.webdriver.support',
    'urllib3.contrib.socks',
    'socks',
    'queue',
    'urllib3.util.retry',
    'urllib3.util.connection',
    'urllib3.util.timeout',
    'urllib3.util.request',
    'urllib3.util.response',
    'urllib3.util.ssl_',
    'urllib3.util.proxy',
    'urllib3.poolmanager',
    'urllib3.connectionpool',
    'urllib3.connection',
    'urllib3.fields',
    'urllib3.filepost',
    'chardet',
    'chardet.universaldetector',
    'idna',
    'idna.core',
    'idna.codec',
    'certifi',
    'charset_normalizer',
    'charset_normalizer.api',
    'charset_normalizer.cli',
    'charset_normalizer.constant',
    'charset_normalizer.models',
    'charset_normalizer.cd',
    'charset_normalizer.md',
    'charset_normalizer.utils',
    'charset_normalizer.legacy',
    'charset_normalizer.version',
    'cryptography',
    'cryptography.fernet',
    'cryptography.hazmat',
    'cryptography.hazmat.backends',
    'cryptography.hazmat.primitives',
    'cryptography.hazmat.primitives.ciphers',
    'cryptography.hazmat.primitives.kdf',
    'cryptography.hazmat.primitives.hashes',
    'cryptography.hazmat.primitives.serialization',
    'cryptography.hazmat.primitives.asymmetric',
    'cffi',
    'cffi.api',
    'cffi.backend_ctypes',
    'cffi.commontypes',
    'cffi.cparser',
    'cffi.ffiplatform',
    'cffi.gc_dlopen',
    'cffi.verifier',
    'cffi._imp_emulation',
    'pycparser',
    'pycparser.ast_transforms',
    'pycparser.c_ast',
    'pycparser.c_generator',
    'pycparser.c_lexer',
    'pycparser.c_parser',
    'pycparser.lextab',
    'pycparser.yacctab',
    'pycparser.ply',
    'pycparser.ply.lex',
    'pycparser.ply.yacc',
    'pycparser.plyparser',
    'pycparser.uncast',
])

block_cipher = None


a = Analysis(
    ['source_code/lanzou_feapder_gui_fixed.py'],
    pathex=['.'],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='lanzou_feapder_gui',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 设置为False，GUI模式
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)